language: go
go:
  - 1.8.x
  - 1.9.x
  - master
go_import_path: github.com/kshvakov/teleport

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/stretchr/testify/assert
  - go get github.com/stretchr/testify/require
script:
  - ./go.test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)